### ISSUE TITLE
Collection of angular metadata freezes the application

### ISSUE THREAD

**Issue by wilkesoftware** [bugsnag/bugsnag-angular#13]
### Expected behavior
No freeze of the application.

### Observed behavior
When an error occurs in an angular component, the metadata gets collected about the component. This leads to the component being stringified. In some circumstances and with complex components, this process leads to circular references, which don't cause an error, but take a really long time to be finished, during which the application is frozen.

In its current state, bugsnag is not usable for us due to this issue.

### Steps to reproduce
It's hard to give an example application in this case, basically any application complex and/or large enough will cause the issue.

### Version
bugsnag-js: 4.6.3
bugsnag-angular: 2.0.1

### Additional information
It would be great to have an option to disable the collection of angular metadata altogether.

#### Can't comment on Issues?
Some users have been unable to comment on Github issues when an [adblocker extension is enabled](https://docs.bugsnag.com/platforms/browsers/faq/#is-bugsnag-blocked-by-ad-blockers).
We recommend temporarily disabling the extension, or if that fails, contacting support@bugsnag.com.

**Comment by bengourley** [comment]
Hey @adickenscheidt are you running your angular application in production mode (using `enableProdMode();` from `@angular/core`? I noticed that most of the debug context is only available in development mode, so the behaviour you describe shouldn't happen in production.

> It would be great to have an option to disable the collection of angular metadata altogether.

I think this is probably a fair request. Let me see what we can do here, and whether or not it makes sense for this library.

**Comment by wilkesoftware** [comment]
Hey @bengourley thanks for the tip! I indeed tested it in this case only with my dev environment, I'll test it out in prod later.
However, we want to use bugsnag in dev mode as well as it makes it easier for us to track bugs while testing, so the problem I described still stands. The suggestion about the option in my aforementioned would still be very useful in our case :)

**Comment by wilkesoftware** [comment]
Accidentally closed the issue, sorry!

**Comment by bengourley** [comment]
> However, we want to use bugsnag in dev mode as well as it makes it easier for us to track bugs while testing, so the problem I described still stands. The suggestion about the option in my aforementioned would still be very useful in our case :)

Understood!

While we get around to this, you should be able to sidestep your current issue by using a `beforeSend` callback to alter the metadata:

```js
// When you configure bugsnag
const bugsnagClient = bugsnag({
  apiKey: 'YOUR_API_KEY',
  beforeSend: (report) => {
    // this removes the entire "angular" metadata
    report.updateMetaData('angular', null)

    // you could also try removing each property individually to see
    // if one is significantly more troublesome that the other
    report.updateMetaData('angular', 'context', null)
    report.updateMetaData('angular', 'component', null)
  }
})
```

The metadata isn't serialized until the point at which the report is about to be sent so removing it at this point should help. Let me know if it does! Cheers

**Comment by bengourley** [comment]
Hey @adickenscheidt I'm going to close this off now that this module is deprecated. We have a ticket on our internal roadmap to address this issue. FYI the new version of this module is over at https://github.com/bugsnag/bugsnag-js/tree/master/packages/plugin-angular.
