### ISSUE TITLE
Does not work when using Ahead of Time compilation

### ISSUE THREAD

**Issue by adrianhuna** [bugsnag/bugsnag-angular#4]
Hi, I experience error when using `angular cli` build process. Don't really know how the build process works but there is a problem with ahead of time compilation.

### Expected behavior
App works when built with [angular cli](https://github.com/angular/angular-cli/) `ng build --prod`. `ng build --prod` turns on `--aot` flag (ahead of time compilation) by default.

### Observed behavior
Does not work with [angular cli](https://github.com/angular/angular-cli/) `ng build --prod` => throws `Uncaught Error: No ErrorHandler. Is platform module (BrowserModule) included?`. 
Everything works fine with development version `ng build` and `ng serve` and production `ng build --prod --aot=false`.

### Version
```
    "@angular/animations": "^5.1.2",
    "@angular/cli": "^1.6.2",
    "@angular/common": "^5.1.2",
    "@angular/compiler": "^5.1.2",
    "@angular/compiler-cli": "^5.1.2",
    "@angular/core": "^5.1.2",
    "@angular/forms": "^5.1.2",
    "@angular/http": "^5.1.2",
    "@angular/platform-browser": "^5.1.2",
    "@angular/platform-browser-dynamic": "^5.1.2",
    "@angular/platform-server": "^5.1.2",
    "@angular/router": "^5.1.2",
    "bugsnag-angular": "^1.0.1",
    "bugsnag-js": "^4.0.3",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.3",
    "hammerjs": "^2.0.8",
    "intl": "^1.2.5",
    "rxjs": "^5.5.6",
    "typescript": "2.4.2",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.18"
```

**Comment by adrianhuna** [comment]
I get the problem also with my plain custom error class so it is unrelated to this lib and thus closing this issue.

**Comment by adrianhuna** [comment]
Sorry, I must reopen the issue. Today I finally got some time to play with my application again. I updated all the libraries (`angular-cli` included), and saw that you pushed new version of `bugsnag-angular`.

You can reproduce the issue with `--aot` flag in your example app too. Steps to reproduce.

1. `git clone git@github.com:bugsnag/bugsnag-angular.git`
1. `cd bugsnag-angular/example`
1. `npm i`
1. `ng serve` and check in browser that everything works as expected
1. now close the server and run `ng serve --aot`. There will not be a compilation error but when you open your browser, you will see `Uncaught Error: No ErrorHandler. Is platform module (BrowserModule) included?` in the browser's console.

-- 

when I run `ng --version`

```
Angular CLI: 1.6.3
Node: 9.2.1
OS: linux x64
Angular: 5.1.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.3
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.5.3
webpack: 3.10.0
```

**Comment by bengourley** [comment]
Hi @adrianhuna thanks for the detailed report. We'll look into this for you.

**Comment by cristiandeschamps** [comment]
Hi, I manage to make it work with AOT, here is my code example. Then import that class in the app.module and follow the documentation for the provide ErrorHandle and useClassAppErrorHandler. 

```js
import { Injectable, ErrorHandler } from '@angular/core';
import { environment } from '../environments/environment';
import bugsnag from 'bugsnag-js';

@Injectable()
export class AppErrorHandler implements ErrorHandler {
    bugsnagClient: any;

    constructor() {
        this.bugsnagClient = bugsnag({
            apiKey: 'YOUR KEY HERE'
        });
    }

    public handleError(error: any) {
        const handledState = {
            severity: 'error',
            severityReason: {type: 'unhandledException'},
            unhandled: true,
        };

        const report = new this.bugsnagClient.BugsnagReport(
            error.name,
            error.message,
            this.bugsnagClient.BugsnagReport.getStacktrace(error),
            handledState,
        );

        if (error.ngDebugContext) {
            report.updateMetaData('angular', {
                component: error.ngDebugContext.component,
                context: error.ngDebugContext.context,
            });
        }

        this.bugsnagClient.notify(report);
    }
}
```

**Comment by bengourley** [comment]
I managed to get the library working with an AOT build by copy+pasting the code from [src/index.ts](/bugsnag/bugsnag-angular/blob/master/src/index.ts) directly into a project and it worked as-is, so it looks like the AOT compiler does not like the .js output that is created by the build.

I tried swapping the `tsc` compiler for `ngc` and equally the AOT compile did not work with the js output.

This seems to require some more work on our part so thanks @cristian-hostpapa for providing a  workaround for now!

**Comment by bengourley** [comment]
Hi @adrianhuna, please could you try out `bugsnag-angular@v2.0.0-1`. Usage has changed so please take a look at the [updated readme](https://github.com/bugsnag/bugsnag-angular/tree/aot).

This works with `ng serve` for me with and without `--aot`.

Let me know how you get on!

**Comment by adrianhuna** [comment]
Hi @bengourley. I can confirm the `v2.0.0-1` version is working with `--aot` mode. Thank you very much!
