### ISSUE TITLE
Not able to run or build with the --prod flag

### ISSUE THREAD

**Issue by RikdeVos** [bugsnag/bugsnag-angular#8]
### Observed behavior
Running the app in --prod gives an error: `Uncaught Error: No ErrorHandler. Is platform module (BrowserModule) included?`

### Steps to reproduce
Run/build the example in production by doing:
`ng serve --prod`

### Version
```
Angular CLI: 1.6.3
Node: 8.3.0
OS: darwin x64
Angular: 5.1.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.3
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.5.3
webpack: 3.10.0
"bugsnag-angular": "^1.0.2",
"bugsnag-js": "^4.0.3",```

**Comment by bengourley** [comment]
Hi @RikdeVos. Please try `v2.0.0` of `bugsnag-angular`, this release should fix the error you are seeing. Let me know if not and I'll reopen. Thanks!
